# Site settings
author: Monica Gerard
title: If the shoe fits...
header-img: img/home-bg.png
email: mlgerardvla@gmail.com
copyright_name: Monica Gerard
description: > # this means to ignore newlines until "baseurl:"
  Doing what comes naturally...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mlgvla

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
